// Mocks generated by Mockito 5.4.4 from annotations
// in grim_fable/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:grim_fable/core/models/adventure.dart' as _i6;
import 'package:grim_fable/core/models/character.dart' as _i4;
import 'package:grim_fable/core/services/ai_service.dart' as _i7;
import 'package:grim_fable/core/services/settings_service.dart' as _i9;
import 'package:grim_fable/features/adventure/adventure_repository.dart' as _i5;
import 'package:grim_fable/features/character/character_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CharacterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRepository extends _i1.Mock
    implements _i2.CharacterRepository {
  MockCharacterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.Character> getAllCharacters() => (super.noSuchMethod(
        Invocation.method(
          #getAllCharacters,
          [],
        ),
        returnValue: <_i4.Character>[],
      ) as List<_i4.Character>);

  @override
  _i3.Future<void> saveCharacter(_i4.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCharacter,
          [character],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCharacter(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AdventureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdventureRepository extends _i1.Mock
    implements _i5.AdventureRepository {
  MockAdventureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i6.Adventure> getAdventuresForCharacter(String? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdventuresForCharacter,
          [characterId],
        ),
        returnValue: <_i6.Adventure>[],
      ) as List<_i6.Adventure>);

  @override
  _i6.Adventure? getLatestAdventure(String? characterId) =>
      (super.noSuchMethod(Invocation.method(
        #getLatestAdventure,
        [characterId],
      )) as _i6.Adventure?);

  @override
  _i3.Future<void> saveAdventure(_i6.Adventure? adventure) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAdventure,
          [adventure],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAdventure(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAdventure,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i7.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> generateResponse(
    String? prompt, {
    String? systemMessage,
    List<Map<String, String>>? history,
    double? temperature,
    int? maxTokens,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [prompt],
          {
            #systemMessage: systemMessage,
            #history: history,
            #temperature: temperature,
            #maxTokens: maxTokens,
          },
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [prompt],
            {
              #systemMessage: systemMessage,
              #history: history,
              #temperature: temperature,
              #maxTokens: maxTokens,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> generateBackstory(String? characterName) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBackstory,
          [characterName],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateBackstory,
            [characterName],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> generateBackstoryUpdate(
    String? currentBackstory,
    String? adventureSummary,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBackstoryUpdate,
          [
            currentBackstory,
            adventureSummary,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateBackstoryUpdate,
            [
              currentBackstory,
              adventureSummary,
            ],
          ),
        )),
      ) as _i3.Future<String>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i9.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String getHfApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getHfApiKey,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getHfApiKey,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<void> setHfApiKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #setHfApiKey,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  double getTemperature() => (super.noSuchMethod(
        Invocation.method(
          #getTemperature,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Future<void> setTemperature(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setTemperature,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getMaxTokens() => (super.noSuchMethod(
        Invocation.method(
          #getMaxTokens,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> setMaxTokens(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setMaxTokens,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String getUiPreset() => (super.noSuchMethod(
        Invocation.method(
          #getUiPreset,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getUiPreset,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<void> setUiPreset(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUiPreset,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool getRecommendedResponsesEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getRecommendedResponsesEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> setRecommendedResponsesEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRecommendedResponsesEnabled,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
