// Mocks generated by Mockito 5.4.4 from annotations
// in grim_fable/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:grim_fable/core/models/adventure.dart' as _i7;
import 'package:grim_fable/core/models/character.dart' as _i5;
import 'package:grim_fable/core/models/saga.dart' as _i9;
import 'package:grim_fable/core/models/saga_progress.dart' as _i10;
import 'package:grim_fable/core/services/ai_service.dart' as _i2;
import 'package:grim_fable/core/services/settings_service.dart' as _i12;
import 'package:grim_fable/features/adventure/adventure_repository.dart' as _i6;
import 'package:grim_fable/features/character/character_repository.dart' as _i3;
import 'package:grim_fable/features/saga/saga_repository.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValidationResult_0 extends _i1.SmartFake
    implements _i2.ValidationResult {
  _FakeValidationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CharacterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRepository extends _i1.Mock
    implements _i3.CharacterRepository {
  MockCharacterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i5.Character> getAllCharacters() => (super.noSuchMethod(
        Invocation.method(
          #getAllCharacters,
          [],
        ),
        returnValue: <_i5.Character>[],
      ) as List<_i5.Character>);

  @override
  _i4.Future<void> saveCharacter(_i5.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCharacter,
          [character],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCharacter(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AdventureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdventureRepository extends _i1.Mock
    implements _i6.AdventureRepository {
  MockAdventureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i7.Adventure> getAdventuresForCharacter(String? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdventuresForCharacter,
          [characterId],
        ),
        returnValue: <_i7.Adventure>[],
      ) as List<_i7.Adventure>);

  @override
  _i7.Adventure? getLatestAdventure(String? characterId) =>
      (super.noSuchMethod(Invocation.method(
        #getLatestAdventure,
        [characterId],
      )) as _i7.Adventure?);

  @override
  _i4.Future<void> saveAdventure(_i7.Adventure? adventure) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAdventure,
          [adventure],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAdventure(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAdventure,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SagaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSagaRepository extends _i1.Mock implements _i8.SagaRepository {
  MockSagaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Saga>> loadSagas() => (super.noSuchMethod(
        Invocation.method(
          #loadSagas,
          [],
        ),
        returnValue: _i4.Future<List<_i9.Saga>>.value(<_i9.Saga>[]),
      ) as _i4.Future<List<_i9.Saga>>);

  @override
  _i10.SagaProgress? getProgress(String? sagaId) =>
      (super.noSuchMethod(Invocation.method(
        #getProgress,
        [sagaId],
      )) as _i10.SagaProgress?);

  @override
  _i4.Future<void> saveProgress(_i10.SagaProgress? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProgress,
          [progress],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProgress(String? sagaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProgress,
          [sagaId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i2.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> generateResponse(
    String? prompt, {
    String? systemMessage,
    List<Map<String, String>>? history,
    double? temperature,
    int? maxTokens,
    double? topP,
    double? frequencyPenalty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateResponse,
          [prompt],
          {
            #systemMessage: systemMessage,
            #history: history,
            #temperature: temperature,
            #maxTokens: maxTokens,
            #topP: topP,
            #frequencyPenalty: frequencyPenalty,
          },
        ),
        returnValue: _i4.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateResponse,
            [prompt],
            {
              #systemMessage: systemMessage,
              #history: history,
              #temperature: temperature,
              #maxTokens: maxTokens,
              #topP: topP,
              #frequencyPenalty: frequencyPenalty,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.ValidationResult> validateIdentity(
    String? name,
    String? occupation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateIdentity,
          [
            name,
            occupation,
          ],
        ),
        returnValue:
            _i4.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #validateIdentity,
            [
              name,
              occupation,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ValidationResult>);

  @override
  _i4.Future<String> generateBackstory(
    String? characterName,
    String? occupation, {
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBackstory,
          [
            characterName,
            occupation,
          ],
          {#description: description},
        ),
        returnValue: _i4.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateBackstory,
            [
              characterName,
              occupation,
            ],
            {#description: description},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateBackstoryUpdate(
    String? currentBackstory,
    String? adventureSummary,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBackstoryUpdate,
          [
            currentBackstory,
            adventureSummary,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateBackstoryUpdate,
            [
              currentBackstory,
              adventureSummary,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateBackstoryAppend(
    String? currentBackstory,
    String? adventureSummary,
    int? sentences,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateBackstoryAppend,
          [
            currentBackstory,
            adventureSummary,
            sentences,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateBackstoryAppend,
            [
              currentBackstory,
              adventureSummary,
              sentences,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateOccupationEvolution(
    String? currentOccupation,
    String? adventureSummary,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateOccupationEvolution,
          [
            currentOccupation,
            adventureSummary,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateOccupationEvolution,
            [
              currentOccupation,
              adventureSummary,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<String>> generateAdventureSuggestions(
    String? characterName,
    String? backstory,
    List<String>? pastAdventureSummaries,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAdventureSuggestions,
          [
            characterName,
            backstory,
            pastAdventureSummaries,
          ],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<int> clarifyGoldAmount(String? context) => (super.noSuchMethod(
        Invocation.method(
          #clarifyGoldAmount,
          [context],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<Map<String, String>> verifyItems(
    List<String>? items,
    String? occupation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyItems,
          [
            items,
            occupation,
          ],
        ),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<({String mainGoal, String title})> generateAdventureTitleAndGoal(
    String? characterName,
    String? backstory,
    String? startingPrompt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAdventureTitleAndGoal,
          [
            characterName,
            backstory,
            startingPrompt,
          ],
        ),
        returnValue: _i4.Future<({String mainGoal, String title})>.value((
          mainGoal: _i11.dummyValue<String>(
            this,
            Invocation.method(
              #generateAdventureTitleAndGoal,
              [
                characterName,
                backstory,
                startingPrompt,
              ],
            ),
          ),
          title: _i11.dummyValue<String>(
            this,
            Invocation.method(
              #generateAdventureTitleAndGoal,
              [
                characterName,
                backstory,
                startingPrompt,
              ],
            ),
          )
        )),
      ) as _i4.Future<({String mainGoal, String title})>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i12.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getHfApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getHfApiKey,
          [],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getHfApiKey,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> setHfApiKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #setHfApiKey,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getTemperature() => (super.noSuchMethod(
        Invocation.method(
          #getTemperature,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setTemperature(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setTemperature,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getMaxTokens() => (super.noSuchMethod(
        Invocation.method(
          #getMaxTokens,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> setMaxTokens(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setMaxTokens,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getTopP() => (super.noSuchMethod(
        Invocation.method(
          #getTopP,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setTopP(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setTopP,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  double getFrequencyPenalty() => (super.noSuchMethod(
        Invocation.method(
          #getFrequencyPenalty,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i4.Future<void> setFrequencyPenalty(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setFrequencyPenalty,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getUiPreset() => (super.noSuchMethod(
        Invocation.method(
          #getUiPreset,
          [],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getUiPreset,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> setUiPreset(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUiPreset,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getRecommendedResponsesEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getRecommendedResponsesEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setRecommendedResponsesEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRecommendedResponsesEnabled,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool getFreeFormInputEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getFreeFormInputEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> setFreeFormInputEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setFreeFormInputEnabled,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
